language: node_js

echo $DOCKER_USERNAME

node_js:
  - 12

services:
  - docker

before_install:
  - docker build -t hello-world-api .

docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: bash docker push gennadiixd/hello-world-ci-cd
  on:
    branch: master
