language: node_js

node_js:
  - 12

services:
  - docker

before_script: 
  - echo $DOCKER_USERNAME

before_install:
  - docker build -t hello-world-api .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
